(source SC)
(source gnu)
(source melpa)
(source org)

(depends-on "ace-jump-mode")
(depends-on "ample-regexps")
(depends-on "anaphora")
(depends-on "apples-mode")
(depends-on "async")
(depends-on "backup-each-save")
(depends-on "cask")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "csharp-mode")
(depends-on "dash")
(depends-on "dash-functional")
(depends-on "debbugs")
(depends-on "direx")
(depends-on "dos")
(depends-on "draft-mode")
(depends-on "el2markdown")
(depends-on "engine-mode" :git "https://github.com/occidens/engine-mode" :branch "experimental")
(depends-on "epl")
(depends-on "ert-runner")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "flx-ido")
(depends-on "flylisp")
(depends-on "fm")
(depends-on "font-lock-studio")
(depends-on "full-ack")
(depends-on "git-annex")
(depends-on "git-timemachine")
(depends-on "git-wip-timemachine")
(depends-on "gitconfig")
(depends-on "graphviz-dot-mode")
(depends-on "hideshow-org" :git "https://github.com/occidens/hideshow-org")
(depends-on "ht")
(depends-on "inf-ruby")
(depends-on "ioccur")
(depends-on "kv")
(depends-on "let-alist")
(depends-on "lex")
(depends-on "lorem-ipsum")
(depends-on "macrostep")
(depends-on "magit")
(depends-on "magit-annex")
(depends-on "magit-gitflow")
(depends-on "markdown-mode+")
(depends-on "mediawiki")
(depends-on "multiple-cursors")
(depends-on "noflet")
(depends-on "org")
(depends-on "org-caldav")
(depends-on "org-grep")
(depends-on "org-jekyll")
(depends-on "org-journal")
(depends-on "org-mac-protocol" :git "https://github.com/occidens/org-mac-protocol" :branch "packaging")
(depends-on "org-octopress")
(depends-on "org-plus-contrib")
(depends-on "org-projectile")
(depends-on "org-sync" :git "git://orgmode.org/org-sync.git")
(depends-on "orglink")
(depends-on "orglue")
(depends-on "outline-magic")
(depends-on "ox-gfm")
(depends-on "ox-mediawiki" :git "https://github.com/tomalexander/orgmode-mediawiki")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "peg")
(depends-on "popup")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rdp")
(depends-on "rich-minority")
(depends-on "rvm")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smart-mode-line")
(depends-on "strie")
(depends-on "sunrise-commander")
(depends-on "sunrise-x-tree")
(depends-on "thingatpt+")
(depends-on "transpose-frame")
(depends-on "workgroups2")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
(depends-on "zotxt")
;;;pallet-ignore

;;(depends-on "simple-call-tree+" :git "https://github.com/vapniks/simple-call-tree-ext.git")

;; Org modules that are neither on MELPA nor in `org-plus-contrib'
(depends-on "ox-mediawiki" :git "https://github.com/tomalexander/orgmode-mediawiki")
(depends-on "org-sync" :git "git://orgmode.org/org-sync.git")

;; Other packages not yet on ELPA or MELPA
;; None at the moment

;; Own versions of published packages
(depends-on "engine-mode" :git "https://github.com/occidens/engine-mode" :branch "experimental")
(depends-on "org-mac-protocol" :git "https://github.com/occidens/org-mac-protocol" :branch "packaging")
(depends-on "hideshow-org" :git "https://github.com/occidens/hideshow-org")

;; Own packages
;(depends-on "rex" :git "rsdn:repos/rex.el.git")
