(source gnu)
(source melpa)
(source org)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "flylisp")
(depends-on "ioccur")
(depends-on "let-alist")
(depends-on "lex")
(depends-on "org-plus-contrib")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "rdp" :git "https://github.com/skeeto/rdp")
(depends-on "workgroups" :git "https://github.com/tlh/workgroups.el")
(depends-on "sunrise-commander" :git "https://github.com/escherdragon/sunrise-commander")
