(source gnu)
(source melpa)
(source org)

(depends-on "cask")
(depends-on "dash")
(depends-on "debbugs")
(depends-on "epl")
(depends-on "f")
(depends-on "flylisp")
(depends-on "ioccur")
(depends-on "let-alist")
(depends-on "lex")
(depends-on "org-plus-contrib")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "peg")
(depends-on "ace-jump-mode")
(depends-on "smart-mode-line")
(depends-on "magit")
(depends-on "magit-annex")
(depends-on "magit-gitflow")
(depends-on "rdp" :git "https://github.com/skeeto/rdp")
(depends-on "workgroups" :git "https://github.com/tlh/workgroups.el")
(depends-on "sunrise-commander" :git "https://github.com/escherdragon/sunrise-commander")
(depends-on "git-annex" :git "https://github.com/jwiegley/git-annex-el")
;;(depends-on "font-lock-studo" :git "https://github.com/Lindydancer/font-lock-studio")
(depends-on "el2markdown" :git "https://github.com/Lindydancer/el2markdown")
(depends-on "rex" :git "rsdn:repos/rex.el.git")
(depends-on "hideshow-org" :git "https://github.com/shanecelis/hideshow-org.git")
(depends-on "strie")
(depends-on "ample-regexps")
(depends-on "org-caldav" :git "https://github.com/dengste/org-caldav.git")
(depends-on "ht")
(depends-on "kv")
